defaults: &defaults
  host: localhost
  port: 27017

development:
  <<: *defaults
  database: shopping_dev

test:
  <<: *defaults
  database: shopping_test

production:
  # <<: *defaults
  # database: shopping_prod
  uri: <%= ENV['MONGOHQ_URL'] %>
